name: Backport on PR Close (Custom)

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  backport:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Custom')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Backport Action (custom targets)
        uses: Nick-v-L/backport@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detection-method: custom
          custom-input: v3.3.x
