name: Backport on PR Close (Custom)

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  backport:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'CUSTOM:')
    runs-on: ubuntu-latest
    steps:
      - name: Run Backport Action (custom targets)
        uses: Nick-v-L/backport@a34b59f66fd70fcce0084c4c482c4f2da04d9ea8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detection-method: custom
          custom-input: v3.3.x
